/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScamRouteImport } from './routes/scam'
import { Route as PropertyVerifyRouteImport } from './routes/property-verify'
import { Route as NoticeCheckRouteImport } from './routes/notice-check'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirIndexRouteImport } from './routes/fir.index'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FirNewRouteImport } from './routes/fir.new'
import { Route as FirIdRouteImport } from './routes/fir.$id'
import { Route as ComplaintsNewRouteImport } from './routes/complaints.new'
import { Route as ComplaintsIdRouteImport } from './routes/complaints.$id'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminFirRouteImport } from './routes/admin/fir'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminComplaintsRouteImport } from './routes/admin/complaints'
import { Route as AdminChatsRouteImport } from './routes/admin/chats'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'
import { Route as ApiSubscriptionsVerifyRouteImport } from './routes/api/subscriptions/verify'
import { Route as ApiSubscriptionsSyncRouteImport } from './routes/api/subscriptions/sync'
import { Route as ApiSubscriptionsCheckoutRouteImport } from './routes/api/subscriptions/checkout'
import { Route as ApiSubscriptionsChangePlanRouteImport } from './routes/api/subscriptions/change-plan'

const ScamRoute = ScamRouteImport.update({
  id: '/scam',
  path: '/scam',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyVerifyRoute = PropertyVerifyRouteImport.update({
  id: '/property-verify',
  path: '/property-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeCheckRoute = NoticeCheckRouteImport.update({
  id: '/notice-check',
  path: '/notice-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirIndexRoute = FirIndexRouteImport.update({
  id: '/fir/',
  path: '/fir/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FirNewRoute = FirNewRouteImport.update({
  id: '/fir/new',
  path: '/fir/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FirIdRoute = FirIdRouteImport.update({
  id: '/fir/$id',
  path: '/fir/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsNewRoute = ComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirRoute = AdminFirRouteImport.update({
  id: '/fir',
  path: '/fir',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsVerifyRoute = ApiSubscriptionsVerifyRouteImport.update({
  id: '/api/subscriptions/verify',
  path: '/api/subscriptions/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsSyncRoute = ApiSubscriptionsSyncRouteImport.update({
  id: '/api/subscriptions/sync',
  path: '/api/subscriptions/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsCheckoutRoute =
  ApiSubscriptionsCheckoutRouteImport.update({
    id: '/api/subscriptions/checkout',
    path: '/api/subscriptions/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubscriptionsChangePlanRoute =
  ApiSubscriptionsChangePlanRouteImport.update({
    id: '/api/subscriptions/change-plan',
    path: '/api/subscriptions/change-plan',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/explain': typeof ExplainRoute
  '/notice-check': typeof NoticeCheckRoute
  '/property-verify': typeof PropertyVerifyRoute
  '/scam': typeof ScamRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fir': typeof AdminFirRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/fir/$id': typeof FirIdRoute
  '/fir/new': typeof FirNewRoute
  '/admin/': typeof AdminIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/fir/': typeof FirIndexRoute
  '/api/subscriptions/change-plan': typeof ApiSubscriptionsChangePlanRoute
  '/api/subscriptions/checkout': typeof ApiSubscriptionsCheckoutRoute
  '/api/subscriptions/sync': typeof ApiSubscriptionsSyncRoute
  '/api/subscriptions/verify': typeof ApiSubscriptionsVerifyRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/explain': typeof ExplainRoute
  '/notice-check': typeof NoticeCheckRoute
  '/property-verify': typeof PropertyVerifyRoute
  '/scam': typeof ScamRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fir': typeof AdminFirRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/fir/$id': typeof FirIdRoute
  '/fir/new': typeof FirNewRoute
  '/admin': typeof AdminIndexRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/fir': typeof FirIndexRoute
  '/api/subscriptions/change-plan': typeof ApiSubscriptionsChangePlanRoute
  '/api/subscriptions/checkout': typeof ApiSubscriptionsCheckoutRoute
  '/api/subscriptions/sync': typeof ApiSubscriptionsSyncRoute
  '/api/subscriptions/verify': typeof ApiSubscriptionsVerifyRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/explain': typeof ExplainRoute
  '/notice-check': typeof NoticeCheckRoute
  '/property-verify': typeof PropertyVerifyRoute
  '/scam': typeof ScamRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fir': typeof AdminFirRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/fir/$id': typeof FirIdRoute
  '/fir/new': typeof FirNewRoute
  '/admin/': typeof AdminIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/fir/': typeof FirIndexRoute
  '/api/subscriptions/change-plan': typeof ApiSubscriptionsChangePlanRoute
  '/api/subscriptions/checkout': typeof ApiSubscriptionsCheckoutRoute
  '/api/subscriptions/sync': typeof ApiSubscriptionsSyncRoute
  '/api/subscriptions/verify': typeof ApiSubscriptionsVerifyRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/explain'
    | '/notice-check'
    | '/property-verify'
    | '/scam'
    | '/admin/chats'
    | '/admin/complaints'
    | '/admin/documents'
    | '/admin/fir'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/analyze'
    | '/api/chat'
    | '/api/generate'
    | '/complaints/$id'
    | '/complaints/new'
    | '/fir/$id'
    | '/fir/new'
    | '/admin/'
    | '/complaints/'
    | '/fir/'
    | '/api/subscriptions/change-plan'
    | '/api/subscriptions/checkout'
    | '/api/subscriptions/sync'
    | '/api/subscriptions/verify'
    | '/api/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/explain'
    | '/notice-check'
    | '/property-verify'
    | '/scam'
    | '/admin/chats'
    | '/admin/complaints'
    | '/admin/documents'
    | '/admin/fir'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/analyze'
    | '/api/chat'
    | '/api/generate'
    | '/complaints/$id'
    | '/complaints/new'
    | '/fir/$id'
    | '/fir/new'
    | '/admin'
    | '/complaints'
    | '/fir'
    | '/api/subscriptions/change-plan'
    | '/api/subscriptions/checkout'
    | '/api/subscriptions/sync'
    | '/api/subscriptions/verify'
    | '/api/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/explain'
    | '/notice-check'
    | '/property-verify'
    | '/scam'
    | '/admin/chats'
    | '/admin/complaints'
    | '/admin/documents'
    | '/admin/fir'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/analyze'
    | '/api/chat'
    | '/api/generate'
    | '/complaints/$id'
    | '/complaints/new'
    | '/fir/$id'
    | '/fir/new'
    | '/admin/'
    | '/complaints/'
    | '/fir/'
    | '/api/subscriptions/change-plan'
    | '/api/subscriptions/checkout'
    | '/api/subscriptions/sync'
    | '/api/subscriptions/verify'
    | '/api/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ExplainRoute: typeof ExplainRoute
  NoticeCheckRoute: typeof NoticeCheckRoute
  PropertyVerifyRoute: typeof PropertyVerifyRoute
  ScamRoute: typeof ScamRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ComplaintsIdRoute: typeof ComplaintsIdRoute
  ComplaintsNewRoute: typeof ComplaintsNewRoute
  FirIdRoute: typeof FirIdRoute
  FirNewRoute: typeof FirNewRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  FirIndexRoute: typeof FirIndexRoute
  ApiSubscriptionsChangePlanRoute: typeof ApiSubscriptionsChangePlanRoute
  ApiSubscriptionsCheckoutRoute: typeof ApiSubscriptionsCheckoutRoute
  ApiSubscriptionsSyncRoute: typeof ApiSubscriptionsSyncRoute
  ApiSubscriptionsVerifyRoute: typeof ApiSubscriptionsVerifyRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scam': {
      id: '/scam'
      path: '/scam'
      fullPath: '/scam'
      preLoaderRoute: typeof ScamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-verify': {
      id: '/property-verify'
      path: '/property-verify'
      fullPath: '/property-verify'
      preLoaderRoute: typeof PropertyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-check': {
      id: '/notice-check'
      path: '/notice-check'
      fullPath: '/notice-check'
      preLoaderRoute: typeof NoticeCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir/': {
      id: '/fir/'
      path: '/fir'
      fullPath: '/fir/'
      preLoaderRoute: typeof FirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fir/new': {
      id: '/fir/new'
      path: '/fir/new'
      fullPath: '/fir/new'
      preLoaderRoute: typeof FirNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir/$id': {
      id: '/fir/$id'
      path: '/fir/$id'
      fullPath: '/fir/$id'
      preLoaderRoute: typeof FirIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/new': {
      id: '/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof ComplaintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fir': {
      id: '/admin/fir'
      path: '/fir'
      fullPath: '/admin/fir'
      preLoaderRoute: typeof AdminFirRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/verify': {
      id: '/api/subscriptions/verify'
      path: '/api/subscriptions/verify'
      fullPath: '/api/subscriptions/verify'
      preLoaderRoute: typeof ApiSubscriptionsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/sync': {
      id: '/api/subscriptions/sync'
      path: '/api/subscriptions/sync'
      fullPath: '/api/subscriptions/sync'
      preLoaderRoute: typeof ApiSubscriptionsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/checkout': {
      id: '/api/subscriptions/checkout'
      path: '/api/subscriptions/checkout'
      fullPath: '/api/subscriptions/checkout'
      preLoaderRoute: typeof ApiSubscriptionsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/change-plan': {
      id: '/api/subscriptions/change-plan'
      path: '/api/subscriptions/change-plan'
      fullPath: '/api/subscriptions/change-plan'
      preLoaderRoute: typeof ApiSubscriptionsChangePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChatsRoute: typeof AdminChatsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFirRoute: typeof AdminFirRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatsRoute: AdminChatsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFirRoute: AdminFirRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ExplainRoute: ExplainRoute,
  NoticeCheckRoute: NoticeCheckRoute,
  PropertyVerifyRoute: PropertyVerifyRoute,
  ScamRoute: ScamRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ComplaintsIdRoute: ComplaintsIdRoute,
  ComplaintsNewRoute: ComplaintsNewRoute,
  FirIdRoute: FirIdRoute,
  FirNewRoute: FirNewRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  FirIndexRoute: FirIndexRoute,
  ApiSubscriptionsChangePlanRoute: ApiSubscriptionsChangePlanRoute,
  ApiSubscriptionsCheckoutRoute: ApiSubscriptionsCheckoutRoute,
  ApiSubscriptionsSyncRoute: ApiSubscriptionsSyncRoute,
  ApiSubscriptionsVerifyRoute: ApiSubscriptionsVerifyRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
