/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScamRouteImport } from './routes/scam'
import { Route as PropertyVerifyRouteImport } from './routes/property-verify'
import { Route as NoticeCheckRouteImport } from './routes/notice-check'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirIndexRouteImport } from './routes/fir.index'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as FirNewRouteImport } from './routes/fir.new'
import { Route as FirIdRouteImport } from './routes/fir.$id'
import { Route as ComplaintsNewRouteImport } from './routes/complaints.new'
import { Route as ComplaintsIdRouteImport } from './routes/complaints.$id'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'

const ScamRoute = ScamRouteImport.update({
  id: '/scam',
  path: '/scam',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyVerifyRoute = PropertyVerifyRouteImport.update({
  id: '/property-verify',
  path: '/property-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeCheckRoute = NoticeCheckRouteImport.update({
  id: '/notice-check',
  path: '/notice-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirIndexRoute = FirIndexRouteImport.update({
  id: '/fir/',
  path: '/fir/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirNewRoute = FirNewRouteImport.update({
  id: '/fir/new',
  path: '/fir/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FirIdRoute = FirIdRouteImport.update({
  id: '/fir/$id',
  path: '/fir/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsNewRoute = ComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/explain': typeof ExplainRoute
  '/notice-check': typeof NoticeCheckRoute
  '/property-verify': typeof PropertyVerifyRoute
  '/scam': typeof ScamRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/fir/$id': typeof FirIdRoute
  '/fir/new': typeof FirNewRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/fir/': typeof FirIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/explain': typeof ExplainRoute
  '/notice-check': typeof NoticeCheckRoute
  '/property-verify': typeof PropertyVerifyRoute
  '/scam': typeof ScamRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/fir/$id': typeof FirIdRoute
  '/fir/new': typeof FirNewRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/fir': typeof FirIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/explain': typeof ExplainRoute
  '/notice-check': typeof NoticeCheckRoute
  '/property-verify': typeof PropertyVerifyRoute
  '/scam': typeof ScamRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/fir/$id': typeof FirIdRoute
  '/fir/new': typeof FirNewRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/fir/': typeof FirIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/explain'
    | '/notice-check'
    | '/property-verify'
    | '/scam'
    | '/api/analyze'
    | '/api/chat'
    | '/api/generate'
    | '/complaints/$id'
    | '/complaints/new'
    | '/fir/$id'
    | '/fir/new'
    | '/complaints/'
    | '/fir/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/explain'
    | '/notice-check'
    | '/property-verify'
    | '/scam'
    | '/api/analyze'
    | '/api/chat'
    | '/api/generate'
    | '/complaints/$id'
    | '/complaints/new'
    | '/fir/$id'
    | '/fir/new'
    | '/complaints'
    | '/fir'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/explain'
    | '/notice-check'
    | '/property-verify'
    | '/scam'
    | '/api/analyze'
    | '/api/chat'
    | '/api/generate'
    | '/complaints/$id'
    | '/complaints/new'
    | '/fir/$id'
    | '/fir/new'
    | '/complaints/'
    | '/fir/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ExplainRoute: typeof ExplainRoute
  NoticeCheckRoute: typeof NoticeCheckRoute
  PropertyVerifyRoute: typeof PropertyVerifyRoute
  ScamRoute: typeof ScamRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ComplaintsIdRoute: typeof ComplaintsIdRoute
  ComplaintsNewRoute: typeof ComplaintsNewRoute
  FirIdRoute: typeof FirIdRoute
  FirNewRoute: typeof FirNewRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  FirIndexRoute: typeof FirIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scam': {
      id: '/scam'
      path: '/scam'
      fullPath: '/scam'
      preLoaderRoute: typeof ScamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-verify': {
      id: '/property-verify'
      path: '/property-verify'
      fullPath: '/property-verify'
      preLoaderRoute: typeof PropertyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-check': {
      id: '/notice-check'
      path: '/notice-check'
      fullPath: '/notice-check'
      preLoaderRoute: typeof NoticeCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir/': {
      id: '/fir/'
      path: '/fir'
      fullPath: '/fir/'
      preLoaderRoute: typeof FirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir/new': {
      id: '/fir/new'
      path: '/fir/new'
      fullPath: '/fir/new'
      preLoaderRoute: typeof FirNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fir/$id': {
      id: '/fir/$id'
      path: '/fir/$id'
      fullPath: '/fir/$id'
      preLoaderRoute: typeof FirIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/new': {
      id: '/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof ComplaintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ExplainRoute: ExplainRoute,
  NoticeCheckRoute: NoticeCheckRoute,
  PropertyVerifyRoute: PropertyVerifyRoute,
  ScamRoute: ScamRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ComplaintsIdRoute: ComplaintsIdRoute,
  ComplaintsNewRoute: ComplaintsNewRoute,
  FirIdRoute: FirIdRoute,
  FirNewRoute: FirNewRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  FirIndexRoute: FirIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
